### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by yhancsx** [yhancsx/slash-landing#1]
- [x] scroll overlay 시 opacity transition
  - section 2,3,4,5 intersection observer > 상하위 섹션 opacity 조정
- [x] section 3,4,5 side nav 
  - [x] toc highlight 더 찾아보기 [codepen](https://codepen.io/saas/pen/LYENgqq), [vuedocs](https://github.com/vuejs/vitepress/blob/16064023cfe390eccc1552792b906156e4936382/src/client/theme-default/composables/outline.ts)
- [x] large pc 마크업
- [x] 모바일버전 마크업
- [x] 모바일버전 nav
- [x] GNB, footer 링크 연결
- [x] header shadow
- [x] pc/mobile 따라 resource 다운로드 최적화 (불필요한것 x)
- [ ] IOS section 4 , 5 레이어 순서 뒤바낌 현상

**Comment by yhancsx** [comment]
## 건의사항
#### 공통
- 앱다운로드 링크? 
- og image ?

#### pc
- section3~5 side nav 위치 
  - 일단 viewport 중앙으로 함.
  - section height이 브라우저 viewport height과 달라서 어색하기도 함
- 스크롤 overay
  - section height이 브라우저 viewport height과 달라서 상단에 딱맞게 고정되지 않음
#### mobile
- js로 하면 화면 깜빡일 수 잇음. media query로 함.
- section3 영상 오른쪽 끝에 파란부분
-
